allow-lan: false
dns:
    enable: true
    enhanced-mode: fake-ip
    nameserver:
        - 119.29.29.29
        - 223.5.5.5
external-controller: 127.0.0.1:9090
log-level: info
mixed-port: 7890
mode: rule
proxies:
    - name: Laxgo
      network: ws
      port: 443
      server: laxgo.zhzz.us.ci
      servername: laxgo.zhzz.us.ci
      skip-cert-verify: false
      tls: true
      type: vless
      udp: true
      uuid: e77f526d-f03e-416d-8856-fb6b511c7eeb
      ws-opts:
        headers:
            Host: laxgo.zhzz.us.ci
        path: /ws
proxy-groups:
    - name: PROXY
      proxies:
        - Laxgo
      type: select
rules:
    - MATCH,PROXY
tun:
    enable: false
    stack: gvisor
    auto-route: true
    auto-detect-interface: true
    dns-hijack:
        - any:53
    strict-route: true
    mtu: 1500
