// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1) {
  return window['go']['main']['App']['AddRule'](arg1);
}

export function CheckTunEnv() {
  return window['go']['main']['App']['CheckTunEnv']();
}

export function ClearBaseConfig() {
  return window['go']['main']['App']['ClearBaseConfig']();
}

export function CloseAllConnections() {
  return window['go']['main']['App']['CloseAllConnections']();
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function ElevatePrivileges() {
  return window['go']['main']['App']['ElevatePrivileges']();
}

export function FixUWPNetwork() {
  return window['go']['main']['App']['FixUWPNetwork']();
}

export function GetAllRules(arg1) {
  return window['go']['main']['App']['GetAllRules'](arg1);
}

export function GetAppBehavior() {
  return window['go']['main']['App']['GetAppBehavior']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetDNSConfig() {
  return window['go']['main']['App']['GetDNSConfig']();
}

export function GetInitialData() {
  return window['go']['main']['App']['GetInitialData']();
}

export function GetLocalConfigs() {
  return window['go']['main']['App']['GetLocalConfigs']();
}

export function GetNetworkConfig() {
  return window['go']['main']['App']['GetNetworkConfig']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRecentLogs() {
  return window['go']['main']['App']['GetRecentLogs']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetSubRecords() {
  return window['go']['main']['App']['GetSubRecords']();
}

export function GetTunConfig() {
  return window['go']['main']['App']['GetTunConfig']();
}

export function GetUwpApps() {
  return window['go']['main']['App']['GetUwpApps']();
}

export function ImportLocalConfig() {
  return window['go']['main']['App']['ImportLocalConfig']();
}

export function InstallTunDriver() {
  return window['go']['main']['App']['InstallTunDriver']();
}

export function OpenConfigFile(arg1) {
  return window['go']['main']['App']['OpenConfigFile'](arg1);
}

export function RenameConfig(arg1, arg2) {
  return window['go']['main']['App']['RenameConfig'](arg1, arg2);
}

export function RunProxy() {
  return window['go']['main']['App']['RunProxy']();
}

export function SaveAppBehavior(arg1) {
  return window['go']['main']['App']['SaveAppBehavior'](arg1);
}

export function SaveConfigsOrder(arg1) {
  return window['go']['main']['App']['SaveConfigsOrder'](arg1);
}

export function SaveDNSConfig(arg1) {
  return window['go']['main']['App']['SaveDNSConfig'](arg1);
}

export function SaveNetworkConfig(arg1) {
  return window['go']['main']['App']['SaveNetworkConfig'](arg1);
}

export function SaveThemePreference(arg1) {
  return window['go']['main']['App']['SaveThemePreference'](arg1);
}

export function SaveTunConfig(arg1) {
  return window['go']['main']['App']['SaveTunConfig'](arg1);
}

export function SaveUwpExemptions(arg1) {
  return window['go']['main']['App']['SaveUwpExemptions'](arg1);
}

export function SearchLogs(arg1) {
  return window['go']['main']['App']['SearchLogs'](arg1);
}

export function SelectLocalConfig(arg1) {
  return window['go']['main']['App']['SelectLocalConfig'](arg1);
}

export function SelectProxy(arg1, arg2) {
  return window['go']['main']['App']['SelectProxy'](arg1, arg2);
}

export function StartConnectionMonitor() {
  return window['go']['main']['App']['StartConnectionMonitor']();
}

export function StartStreamingLogs() {
  return window['go']['main']['App']['StartStreamingLogs']();
}

export function StartTrafficStream() {
  return window['go']['main']['App']['StartTrafficStream']();
}

export function StopConnectionMonitor() {
  return window['go']['main']['App']['StopConnectionMonitor']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function StopStreamingLogs() {
  return window['go']['main']['App']['StopStreamingLogs']();
}

export function StopTrafficStream() {
  return window['go']['main']['App']['StopTrafficStream']();
}

export function SyncState() {
  return window['go']['main']['App']['SyncState']();
}

export function TestAllProxies(arg1) {
  return window['go']['main']['App']['TestAllProxies'](arg1);
}

export function ToggleSystemProxy(arg1) {
  return window['go']['main']['App']['ToggleSystemProxy'](arg1);
}

export function ToggleTunMode(arg1) {
  return window['go']['main']['App']['ToggleTunMode'](arg1);
}

export function UpdateAllSubs() {
  return window['go']['main']['App']['UpdateAllSubs']();
}

export function UpdateClashMode(arg1) {
  return window['go']['main']['App']['UpdateClashMode'](arg1);
}

export function UpdateSingleSub(arg1) {
  return window['go']['main']['App']['UpdateSingleSub'](arg1);
}

export function UpdateSub(arg1) {
  return window['go']['main']['App']['UpdateSub'](arg1);
}
