// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAppUpdate(arg1) {
  return window['go']['main']['App']['ApplyAppUpdate'](arg1);
}

export function AutoCheckAndDownloadAppUpdateAsync() {
  return window['go']['main']['App']['AutoCheckAndDownloadAppUpdateAsync']();
}

export function CheckAndDownloadAppUpdateAsync() {
  return window['go']['main']['App']['CheckAndDownloadAppUpdateAsync']();
}

export function CheckCoreUpdateAsync() {
  return window['go']['main']['App']['CheckCoreUpdateAsync']();
}

export function CheckTunEnv() {
  return window['go']['main']['App']['CheckTunEnv']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CloseAllConnections() {
  return window['go']['main']['App']['CloseAllConnections']();
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DoLocalImport(arg1, arg2) {
  return window['go']['main']['App']['DoLocalImport'](arg1, arg2);
}

export function ElevatePrivileges() {
  return window['go']['main']['App']['ElevatePrivileges']();
}

export function ExecuteRestore(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRestore'](arg1, arg2);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function FixUWPNetwork() {
  return window['go']['main']['App']['FixUWPNetwork']();
}

export function FlashWindow() {
  return window['go']['main']['App']['FlashWindow']();
}

export function FlushFakeIP() {
  return window['go']['main']['App']['FlushFakeIP']();
}

export function GetActiveGeoUpdates() {
  return window['go']['main']['App']['GetActiveGeoUpdates']();
}

export function GetAppBehavior() {
  return window['go']['main']['App']['GetAppBehavior']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetComponentFileInfo() {
  return window['go']['main']['App']['GetComponentFileInfo']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetCoreVersion() {
  return window['go']['main']['App']['GetCoreVersion']();
}

export function GetCustomRules(arg1) {
  return window['go']['main']['App']['GetCustomRules'](arg1);
}

export function GetDNSConfig() {
  return window['go']['main']['App']['GetDNSConfig']();
}

export function GetInitialData() {
  return window['go']['main']['App']['GetInitialData']();
}

export function GetLocalConfigs() {
  return window['go']['main']['App']['GetLocalConfigs']();
}

export function GetNetworkConfig() {
  return window['go']['main']['App']['GetNetworkConfig']();
}

export function GetProxyDelay(arg1, arg2) {
  return window['go']['main']['App']['GetProxyDelay'](arg1, arg2);
}

export function GetRecentLogs() {
  return window['go']['main']['App']['GetRecentLogs']();
}

export function GetTunConfig() {
  return window['go']['main']['App']['GetTunConfig']();
}

export function GetUwpApps() {
  return window['go']['main']['App']['GetUwpApps']();
}

export function GetWintunVersion() {
  return window['go']['main']['App']['GetWintunVersion']();
}

export function HideMainWindow() {
  return window['go']['main']['App']['HideMainWindow']();
}

export function InstallTunDriverAsync(arg1) {
  return window['go']['main']['App']['InstallTunDriverAsync'](arg1);
}

export function ManualCheckAppUpdate() {
  return window['go']['main']['App']['ManualCheckAppUpdate']();
}

export function OpenConfigFile(arg1) {
  return window['go']['main']['App']['OpenConfigFile'](arg1);
}

export function RenameConfig(arg1, arg2) {
  return window['go']['main']['App']['RenameConfig'](arg1, arg2);
}

export function ResetComponentSettings(arg1) {
  return window['go']['main']['App']['ResetComponentSettings'](arg1);
}

export function RestartCore() {
  return window['go']['main']['App']['RestartCore']();
}

export function SaveAppBehavior(arg1) {
  return window['go']['main']['App']['SaveAppBehavior'](arg1);
}

export function SaveCustomRules(arg1, arg2) {
  return window['go']['main']['App']['SaveCustomRules'](arg1, arg2);
}

export function SaveDNSConfig(arg1) {
  return window['go']['main']['App']['SaveDNSConfig'](arg1);
}

export function SaveNetworkConfig(arg1) {
  return window['go']['main']['App']['SaveNetworkConfig'](arg1);
}

export function SaveThemePreference(arg1) {
  return window['go']['main']['App']['SaveThemePreference'](arg1);
}

export function SaveTunConfig(arg1) {
  return window['go']['main']['App']['SaveTunConfig'](arg1);
}

export function SaveUwpExemptions(arg1) {
  return window['go']['main']['App']['SaveUwpExemptions'](arg1);
}

export function SearchLogs(arg1) {
  return window['go']['main']['App']['SearchLogs'](arg1);
}

export function SelectBackupFile() {
  return window['go']['main']['App']['SelectBackupFile']();
}

export function SelectLocalConfig(arg1) {
  return window['go']['main']['App']['SelectLocalConfig'](arg1);
}

export function SelectLocalFile() {
  return window['go']['main']['App']['SelectLocalFile']();
}

export function SelectProxy(arg1, arg2) {
  return window['go']['main']['App']['SelectProxy'](arg1, arg2);
}

export function SetupSystray() {
  return window['go']['main']['App']['SetupSystray']();
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function StartClash(arg1) {
  return window['go']['main']['App']['StartClash'](arg1);
}

export function StartConnectionMonitor() {
  return window['go']['main']['App']['StartConnectionMonitor']();
}

export function StartStreamingLogs() {
  return window['go']['main']['App']['StartStreamingLogs']();
}

export function StopConnectionMonitor() {
  return window['go']['main']['App']['StopConnectionMonitor']();
}

export function StopStreamingLogs() {
  return window['go']['main']['App']['StopStreamingLogs']();
}

export function SyncRules(arg1) {
  return window['go']['main']['App']['SyncRules'](arg1);
}

export function SyncState() {
  return window['go']['main']['App']['SyncState']();
}

export function TestAllProxies(arg1) {
  return window['go']['main']['App']['TestAllProxies'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}

export function ToggleMainWindow() {
  return window['go']['main']['App']['ToggleMainWindow']();
}

export function ToggleSystemProxy(arg1) {
  return window['go']['main']['App']['ToggleSystemProxy'](arg1);
}

export function ToggleTunMode(arg1) {
  return window['go']['main']['App']['ToggleTunMode'](arg1);
}

export function UpdateAllGeoDatabasesAsync() {
  return window['go']['main']['App']['UpdateAllGeoDatabasesAsync']();
}

export function UpdateAllSubsAsync() {
  return window['go']['main']['App']['UpdateAllSubsAsync']();
}

export function UpdateClashMode(arg1) {
  return window['go']['main']['App']['UpdateClashMode'](arg1);
}

export function UpdateCoreComponentAsync() {
  return window['go']['main']['App']['UpdateCoreComponentAsync']();
}

export function UpdateGeoDatabaseAsync(arg1) {
  return window['go']['main']['App']['UpdateGeoDatabaseAsync'](arg1);
}

export function UpdateSingleSub(arg1) {
  return window['go']['main']['App']['UpdateSingleSub'](arg1);
}

export function UpdateSub(arg1, arg2) {
  return window['go']['main']['App']['UpdateSub'](arg1, arg2);
}
