// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clash} from '../models';

export function CheckTunEnv():Promise<Record<string, boolean>>;

export function FixUWPNetwork():Promise<void>;

export function GetInitialData():Promise<Record<string, any>>;

export function GetProxyStatus():Promise<boolean>;

export function GetTunConfig():Promise<clash.TunConfig>;

export function InstallTunDriver():Promise<void>;

export function RunProxy():Promise<void>;

export function SaveTunConfig(arg1:clash.TunConfig):Promise<void>;

export function SelectProxy(arg1:string,arg2:string):Promise<void>;

export function SetConfigMode(arg1:string):Promise<void>;

export function StartStreamingLogs():Promise<void>;

export function StartTrafficStream():Promise<void>;

export function StopProxy():Promise<void>;

export function StopStreamingLogs():Promise<void>;

export function StopTrafficStream():Promise<void>;

export function TestAllProxies(arg1:Array<string>):Promise<void>;

export function UpdateSub(arg1:string):Promise<void>;
