// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTunEnv() {
  return window['go']['main']['App']['CheckTunEnv']();
}

export function ClearBaseConfig() {
  return window['go']['main']['App']['ClearBaseConfig']();
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function FixUWPNetwork() {
  return window['go']['main']['App']['FixUWPNetwork']();
}

export function GetDNSConfig() {
  return window['go']['main']['App']['GetDNSConfig']();
}

export function GetInitialData() {
  return window['go']['main']['App']['GetInitialData']();
}

export function GetLocalConfigs() {
  return window['go']['main']['App']['GetLocalConfigs']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetTunConfig() {
  return window['go']['main']['App']['GetTunConfig']();
}

export function ImportLocalConfig() {
  return window['go']['main']['App']['ImportLocalConfig']();
}

export function InstallTunDriver() {
  return window['go']['main']['App']['InstallTunDriver']();
}

export function OpenConfigFile(arg1) {
  return window['go']['main']['App']['OpenConfigFile'](arg1);
}

export function RenameConfig(arg1, arg2) {
  return window['go']['main']['App']['RenameConfig'](arg1, arg2);
}

export function RunProxy() {
  return window['go']['main']['App']['RunProxy']();
}

export function SaveDNSConfig(arg1) {
  return window['go']['main']['App']['SaveDNSConfig'](arg1);
}

export function SaveTunConfig(arg1) {
  return window['go']['main']['App']['SaveTunConfig'](arg1);
}

export function SelectLocalConfig(arg1) {
  return window['go']['main']['App']['SelectLocalConfig'](arg1);
}

export function SelectProxy(arg1, arg2) {
  return window['go']['main']['App']['SelectProxy'](arg1, arg2);
}

export function SetConfigMode(arg1) {
  return window['go']['main']['App']['SetConfigMode'](arg1);
}

export function StartStreamingLogs() {
  return window['go']['main']['App']['StartStreamingLogs']();
}

export function StartTrafficStream() {
  return window['go']['main']['App']['StartTrafficStream']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function StopStreamingLogs() {
  return window['go']['main']['App']['StopStreamingLogs']();
}

export function StopTrafficStream() {
  return window['go']['main']['App']['StopTrafficStream']();
}

export function TestAllProxies(arg1) {
  return window['go']['main']['App']['TestAllProxies'](arg1);
}

export function UpdateSub(arg1) {
  return window['go']['main']['App']['UpdateSub'](arg1);
}
