// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clash} from '../models';

export function CheckTunEnv():Promise<Record<string, boolean>>;

export function GetInitialData():Promise<Record<string, any>>;

export function GetNodeDelay(arg1:string,arg2:string):Promise<number>;

export function GetOfflineDelay(arg1:string):Promise<number>;

export function GetProxyNodes():Promise<Array<clash.ProxyNode>>;

export function GetProxyStatus():Promise<boolean>;

export function RunProxy():Promise<string>;

export function SelectProxy(arg1:string,arg2:string):Promise<string>;

export function SetConfigMode(arg1:string):Promise<string>;

export function StartAsyncTest(arg1:string):Promise<string>;

export function StartStreamingLogs():Promise<void>;

export function StopProxy():Promise<string>;

export function UpdateClashSettings(arg1:Record<string, any>):Promise<string>;

export function UpdateSubscription(arg1:string,arg2:string):Promise<string>;
