// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {clash} from '../models';
import {logger} from '../models';

export function AddRule(arg1:string):Promise<void>;

export function CheckTunEnv():Promise<Record<string, boolean>>;

export function ClearBaseConfig():Promise<void>;

export function CloseAllConnections():Promise<void>;

export function CloseConnection(arg1:string):Promise<void>;

export function DeleteConfig(arg1:string):Promise<void>;

export function DeleteRule(arg1:number):Promise<void>;

export function ElevatePrivileges():Promise<void>;

export function FixUWPNetwork():Promise<void>;

export function GetAppBehavior():Promise<main.AppBehavior>;

export function GetConnections():Promise<Record<string, any>>;

export function GetDNSConfig():Promise<clash.DNSConfig>;

export function GetInitialData():Promise<Record<string, any>>;

export function GetLocalConfigs():Promise<Array<string>>;

export function GetNetworkConfig():Promise<clash.NetworkConfig>;

export function GetProxyStatus():Promise<main.ProxyStatus>;

export function GetRecentLogs():Promise<Array<logger.LogEntry>>;

export function GetRules():Promise<clash.RuleInfo>;

export function GetSubRecords():Promise<Record<string, main.SubRecord>>;

export function GetTunConfig():Promise<clash.TunConfig>;

export function ImportLocalConfig():Promise<void>;

export function InstallTunDriver():Promise<void>;

export function OpenConfigFile(arg1:string):Promise<void>;

export function RenameConfig(arg1:string,arg2:string):Promise<void>;

export function RunProxy():Promise<void>;

export function SaveAppBehavior(arg1:main.AppBehavior):Promise<void>;

export function SaveConfigsOrder(arg1:Array<string>):Promise<void>;

export function SaveDNSConfig(arg1:clash.DNSConfig):Promise<void>;

export function SaveNetworkConfig(arg1:clash.NetworkConfig):Promise<void>;

export function SaveThemePreference(arg1:boolean):Promise<void>;

export function SaveTunConfig(arg1:clash.TunConfig):Promise<void>;

export function SearchLogs(arg1:string):Promise<Array<logger.LogEntry>>;

export function SelectLocalConfig(arg1:string):Promise<void>;

export function SelectProxy(arg1:string,arg2:string):Promise<void>;

export function StartConnectionMonitor():Promise<void>;

export function StartStreamingLogs():Promise<void>;

export function StartTrafficStream():Promise<void>;

export function StopConnectionMonitor():Promise<void>;

export function StopProxy():Promise<void>;

export function StopStreamingLogs():Promise<void>;

export function StopTrafficStream():Promise<void>;

export function SyncState():Promise<void>;

export function TestAllProxies(arg1:Array<string>):Promise<void>;

export function ToggleSystemProxy(arg1:boolean):Promise<void>;

export function ToggleTunMode(arg1:boolean):Promise<void>;

export function UpdateAllSubs():Promise<void>;

export function UpdateClashMode(arg1:string):Promise<void>;

export function UpdateSingleSub(arg1:string):Promise<void>;

export function UpdateSub(arg1:string):Promise<void>;
